# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f70ff2bea5778919880d3ec77f0c882ad969fdba7a105721a1276ac94947c0f2b8734e684aff27bb473eb9f3bfa436803e3d2935ca2848abd655022374279a79

test:
  secret_key_base: 3653bf749074858e9e4ef5b64daec171a8c7812983db99c82271d87c28c1cf0ed58ef4f519189ed31a2b0b1dd9129441108cb30c6e6ea0f18e2eb391d858cbde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
